version: "3.9"

services:
  app:
    build: .
    container_name: kurshax-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/DBForKurs2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
    ports:
      - "8080:8080"

volumes:
  pgdata:
